version: '2.4'
services:
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: foodfy
    ports:
    - "5432:5432"
    volumes:
    - foodfy_data:/var/lib/postgres

volumes:
  foodfy_data: