server:
  error:
    include-stacktrace: on_param

spring:
  application:
    name: foodfy
  datasource:
    url: jdbc:postgresql://localhost:5432/foodfy
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
